### PR TITLE
Link support

### PR DESCRIPTION
**Pull request by Bitseat**

### CODE REVIEW

**Comment by ngeiswei** [comment]
@Bitseat, I'm getting an error about `No such file or directory` about `atom_type.h`. Do you get this as well? If not, please clean up your system (you may use https://github.com/ngeiswei/ocbld `ocbld uninstall` if you wish).

**Comment by Bitseat** [comment]
@ngeiswei , the updated branch works perfectly on my machine. I tried cleaning the build directory and also did `ocbld uninstall`. everything builds 100% both on CLion and with `octool -b`. I wonder why it still can't find `<opencog/atomese/atom_types/atom_types.h>` and fails here.

**Comment by ngeiswei** [comment]
Works fine for me as well. Not sure what to do... However before merging, please add one or more unit tests in `InterpreterUTest.cxxtest`, thanks.

**Comment by Bitseat** [comment]
included in #89

**Comment by ngeiswei** [comment]
@Bitseat, I am not sure whether you've intentionally reopened that PR or github automatically reopened after you've pushed some commit on it. Please close if it was non-intentional, or explain otherwise.

**Pull request closed without merging**
